In [1]:
import numpy as np

In [3]:
a = np.array([6,7,8,9])

In [4]:
a[0:2]

array([6, 7])

In [5]:
a[2:]

array([8, 9])

In [6]:
a[-1]
a[-2]

8

In [7]:
b = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [8]:
b[1][2]

6

In [9]:
b[1,2]

6

In [10]:
b[2,0]

7

In [11]:
b[-1]

array([7, 8, 9])

In [12]:
b[-1, 0:2]

array([7, 8])

In [13]:
b[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [15]:
# Customer ID, Name
c = np.array([
    [101, "Mira"],
    [102, "Abdul"],
    [103, "Andrea"]
])
#Customer ID, Purchase Amount, Purchase Date
d = np.array([
    [101, 250.50, '2023-08-01'],
    [102, 150.00, '2023-08-02'],
    [103, 300.75, '2023-08-01']
])

In [20]:
#To combine two arrays in a horizontal manner (adding it to the end of it):
np.hstack((c,d))

array([['101', 'Mira', '101', '250.5', '2023-08-01'],
       ['102', 'Abdul', '102', '150.0', '2023-08-02'],
       ['103', 'Andrea', '103', '300.75', '2023-08-01']], dtype='<U32')

In [21]:
c

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea']], dtype='<U21')

In [22]:
e = np.array([
    [104, 'Venkat'],
    [105, 'John'],
    [106, 'Kathy']
])

In [23]:
np.vstack((c,e))

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea'],
       ['104', 'Venkat'],
       ['105', 'John'],
       ['106', 'Kathy']], dtype='<U21')

In [28]:
transactions = np.array([
    [101, 'Mohan', 250.50, '2023-08-01'],
    [102, 'Bob', 150.00, '2023-08-02'],
    [103, 'Fatima', 300.75, '2023-08-01'],
    [104, 'David', 400.20, '2023-08-03'],
    [105, 'Aryan', 330.1, '2023-08-04'],
])

#This will split it horizontally, and the number will be columns because it's a horizontal split
a,b = np.hsplit(transactions, [2])

In [29]:
a

array([['101', 'Mohan'],
       ['102', 'Bob'],
       ['103', 'Fatima'],
       ['104', 'David'],
       ['105', 'Aryan']], dtype='<U32')

In [30]:
b

array([['250.5', '2023-08-01'],
       ['150.0', '2023-08-02'],
       ['300.75', '2023-08-01'],
       ['400.2', '2023-08-03'],
       ['330.1', '2023-08-04']], dtype='<U32')

In [36]:
x,y = np.vsplit(transactions, [2])

In [37]:
x

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02']], dtype='<U32')

In [38]:
y

array([['103', 'Fatima', '300.75', '2023-08-01'],
       ['104', 'David', '400.2', '2023-08-03'],
       ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')

In [39]:
monthly_sales = np.array([30, 33, 35, 28, 42])

In [40]:
# To see when you hit a specific threshold or not:
result = monthly_sales > 32
result

array([False,  True,  True, False,  True])

In [42]:
#This will tell us the revenues when it was true
monthly_sales[result]

array([33, 35, 42])

In [43]:
monthly_sales.max()

42

In [44]:
# Gives us the index of the maximum value
np.argmax(monthly_sales)

4

In [45]:
transactions

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02'],
       ['103', 'Fatima', '300.75', '2023-08-01'],
       ['104', 'David', '400.2', '2023-08-03'],
       ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')

In [48]:
t_index = np.argmax(transactions[:,2].astype(float))

In [49]:
t_index

3

In [50]:
transactions[t_index]

array(['104', 'David', '400.2', '2023-08-03'], dtype='<U32')

In [51]:
transactions[:,0]

array(['101', '102', '103', '104', '105'], dtype='<U32')

In [52]:
transactions[transactions[:,0]=='102']

array([['102', 'Bob', '150.0', '2023-08-02']], dtype='<U32')