In [1]:
import numpy as np

In [2]:
rev_q1 = np.array([10,12,9])

In [3]:
# no. of dimensions
rev_q1.ndim

1

In [4]:
rev = np.array([[10,12,9],[15,11,13]])
rev.ndim

2

In [5]:
#Indexing
rev[1,0]

15

In [6]:
rev[1,2]

13

In [7]:
rev[1,2] = 14

In [8]:
rev

array([[10, 12,  9],
       [15, 11, 14]])

In [9]:
rev.dtype

dtype('int64')

In [10]:
#The memory each of them takes up 
rev.itemsize

8

In [11]:
#The size of the array
rev.size

6

In [12]:
#Rows and columns
rev.shape

(2, 3)

In [13]:
np.sort(rev)

array([[ 9, 10, 12],
       [11, 14, 15]])

In [14]:
#To see it in ascending order
np.sort(rev, axis=None)

array([ 9, 10, 11, 12, 14, 15])

In [15]:
#Empty array
#Useful for neural networks because they can be used for the weights
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.arange(23,30)

array([23, 24, 25, 26, 27, 28, 29])

In [21]:
#The last number is how much it increments
np.arange(23,30, 2)

array([23, 25, 27, 29])

In [23]:
#You can also say how many number you want total between what range and it will do the math
np.linspace(10,20,3)

array([10., 15., 20.])

In [24]:
rev

array([[10, 12,  9],
       [15, 11, 14]])

In [25]:
#If you want to flatten the array 
rev.ravel()

array([10, 12,  9, 15, 11, 14])

In [26]:
#Same as ravel, but returns a new array
rev.flatten()

array([10, 12,  9, 15, 11, 14])

In [27]:
#You can change the column and row features 
rev.reshape(3,2)

array([[10, 12],
       [ 9, 15],
       [11, 14]])

In [28]:
rev

array([[10, 12,  9],
       [15, 11, 14]])

In [29]:
rev.min()

9

In [30]:
rev.max()

15

In [31]:
#axis = 1 means it will sum up by the row
rev.sum(axis=1)

array([31, 40])

In [32]:
#axis = 0 means it will sum up by the columns
rev.sum(axis=0)

array([25, 23, 23])

In [33]:
for row in rev:
    print("row:-> ", row)

row:->  [10 12  9]
row:->  [15 11 14]


In [34]:
b = np.array([1,4,16])

In [36]:
np.sqrt(b)

array([1., 2., 4.])

In [37]:
np.square(b)

array([  1,  16, 256])

In [39]:
#All this information can be found in the NumPy documentation page