In [1]:
import numpy as np

In [6]:
#Sales Data for Quarter 1 and Quarter 2
#Rows represent different products, columns represent different regions

q1 = np.array([
#    US  IND CHINA
    [200,220,250], # Product A - iPhone
    [150,180,210], # Product B - iPad
    [300,330,360]  # Product C - Macbook
])

q2 = np.array([
#    USA  IND CHINA
    [209,231,259], # Product A - iPhone
    [155,192,222], # Product B - iPad
    [310,340,375]  # Product C - Macbook
])

In [8]:
#Combining sales done in both quarters
q1 + q2

array([[409, 451, 509],
       [305, 372, 432],
       [610, 670, 735]])

In [9]:
#Finding the difference between the quarters
q2 - q1

array([[ 9, 11,  9],
       [ 5, 12, 12],
       [10, 10, 15]])

In [10]:
#Finding the percentage increase
(q2-q1)*100/q1

array([[4.5       , 5.        , 3.6       ],
       [3.33333333, 6.66666667, 5.71428571],
       [3.33333333, 3.03030303, 4.16666667]])

In [14]:
prices = np.array([
#    USA  IND CHINA
    [10, 12, 11], # Prices for Product A - iPhone
    [8,  9,  10], # Prices for Product B - iPad
    [15, 16, 17]  # Prices for Product C - MacBook
])

q1_revenue = q1 * prices
q1_revenue

array([[2000, 2640, 2750],
       [1200, 1620, 2100],
       [4500, 5280, 6120]])

In [17]:
q1_discounts = q1_revenue*0.2
q1_discounts

array([[ 400.,  528.,  550.],
       [ 240.,  324.,  420.],
       [ 900., 1056., 1224.]])

In [18]:
#revenue - discount is the net revenue
net_revenue = q1_revenue - q1_discounts
net_revenue

array([[1600., 2112., 2200.],
       [ 960., 1296., 1680.],
       [3600., 4224., 4896.]])

In [19]:
np.sum(q1_discounts)

5642.0

In [20]:
np.sum(net_revenue)

22568.0

In [24]:
features = np.array([
    [2000, 3], # house 1 - sqaure feet and bedrooms
    [1800, 2]  # house 2 - sqaure feet and bedrooms
])

#Weights is the metric that can be used to caclulate the price 
weights = np.array([150, 50000])

#Does dot product on the two matrices 
np.dot(features, weights)

array([450000, 370000])

In [25]:
c = np.array([1,2,3])
d = np.array([4,5,6])

#Does cross product on the two matrices 
np.cross(c,d)

array([-3,  6, -3])